version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insightlens
      - FLASK_SECRET_KEY=your_secret_key
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insightlens
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: